all:
  children:
    kvm_hosts:
      hosts:
        localhost:
          ansible_connection: local
    provisioned_vms:
      hosts: {}
    db:
      hosts: {}
    dev:
      hosts: {}
    prod:
      hosts: {}
    monitoring:
      hosts: {}
    nominatim:
      hosts: {}
