all:
  children:
    kvm_hosts:
      hosts:
        192.168.1.118:
          ansible_user: oklab
    provisioned_vms:
      hosts: {}
    db:
      hosts: {}
    dev:
      hosts: {}
    prod:
      hosts: {}
    monitoring:
      hosts: {}
    nominatim:
      hosts: {}
