all:
  children:
    provisioned_vms:
      hosts:
        db01:
          ansible_host: 192.168.122.148
          ansible_user: ubuntu
          ansible_ssh_common_args: "-o ProxyJump=oklab@192.168.216.84"
          ansible_become: true
          ansible_become_method: sudo
        dev01:
          ansible_host: 192.168.122.103
          ansible_user: ubuntu
          ansible_ssh_common_args: "-o ProxyJump=oklab@192.168.216.84"
          ansible_become: true
          ansible_become_method: sudo
        mon01:
          ansible_host: 192.168.122.72
          ansible_user: ubuntu
          ansible_ssh_common_args: "-o ProxyJump=oklab@192.168.216.84"
          ansible_become: true
          ansible_become_method: sudo
        nom01:
          ansible_host: 192.168.122.183
          ansible_user: ubuntu
          ansible_ssh_common_args: "-o ProxyJump=oklab@192.168.216.84"
          ansible_become: true
          ansible_become_method: sudo
        prod01:
          ansible_host: 192.168.122.20
          ansible_user: ubuntu
          ansible_ssh_common_args: "-o ProxyJump=oklab@192.168.216.84"
          ansible_become: true
          ansible_become_method: sudo
    db:
      hosts:
        db01: {}
    dev:
      hosts:
        dev01: {}
    prod:
      hosts:
        prod01: {}
    monitoring:
      hosts:
        mon01: {}
    nominatim:
      hosts:
        nom01: {}
