all:
  children:
    provisioned_vms:
      hosts:
        db01:
          ansible_host: 192.168.122.249
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_become: true
          ansible_become_method: sudo
        mon01:
          ansible_host: 192.168.122.241
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_become: true
          ansible_become_method: sudo
        nom01:
          ansible_host: 192.168.122.10
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_become: true
          ansible_become_method: sudo
    db:
      hosts:
        db01: {}
    dev:
      hosts:
    prod:
      hosts:
    monitoring:
      hosts:
        mon01: {}
    nominatim:
      hosts:
        nom01: {}
